In [2]:
from sklearn.svm import SVC
import numpy as np

x=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

clf=SVC(C=1e5,kernel='linear')
clf.fit(x,y)

print('w= ',clf.coef_)
print('b= ',clf.intercept_)
print('Indices of support vectors = ',clf.support_)
print('Support vectors = ',clf.support_vectors_)
print('Number of support vectors for each class = ',clf.n_support_)
print('Coefficients of the support vector in the decision function = ',np.abs(clf.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors =  [2 3]
Support vectors =  [[ 2.  3.]
 [ 6. -1.]]
Number of support vectors for each class =  [1 1]
Coefficients of the support vector in the decision function =  [[0.0625 0.0625]]


In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
df=pd.read_csv("glass.csv")
print(df)

      Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe  Type
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 11 columns]


In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df))

[[-1.72397593  0.87286765  0.28495326 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.70778837 -0.24933347  0.59181718 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.6916008  -0.72131806  0.14993314 ... -0.35287683 -0.5864509
  -0.84827468]
 ...
 [ 1.6916008   0.75404635  1.16872135 ...  2.95320036 -0.5864509
   2.01047778]
 [ 1.70778837 -0.61239854  1.19327046 ...  2.81208731 -0.5864509
   2.01047778]
 [ 1.72397593 -0.41436305  1.00915211 ...  3.01367739 -0.5864509
   2.01047778]]


In [6]:
x=df.drop('Type',axis=1)
y=df.Type

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [8]:
from sklearn import svm
ml=svm.SVC(kernel='linear')
ml.fit(x_train,y_train)

SVC(kernel='linear')

In [9]:
print(ml.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.62000e+02 1.51934e+00 1.36400e+01 3.54000e+00 7.50000e-01 7.26500e+01
  1.60000e-01 8.89000e+00 1.50000e-01 2.40000e-01]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.76000e+02 1.52119e+00 1.29700e+01 3.30000e-01 1.51000e+00 7.33900e+01
  1.30000e-01 1.12700e+01 0.00000e+00 2.80000e-01]


In [10]:
print(ml.n_support_)

[1 2 3 3 3 1]


In [11]:
y_pred=ml.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))

0.9846153846153847


In [13]:
print(confusion_matrix(y_test,y_pred))

[[24  0  0  0  0  0]
 [ 0 22  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  0  4  0]
 [ 0  0  0  0  0  8]]


In [14]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        22
           3       0.83      1.00      0.91         5
           5       1.00      0.50      0.67         2
           6       1.00      1.00      1.00         4
           7       1.00      1.00      1.00         8

    accuracy                           0.98        65
   macro avg       0.97      0.92      0.93        65
weighted avg       0.99      0.98      0.98        65



In [15]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [16]:
#With Different Kernels

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [17]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

In [18]:
print(accuracy_score(y_test,ypred1))

0.6923076923076923


In [19]:
print(accuracy_score(y_test,ypred2))

0.9230769230769231


In [20]:
print(accuracy_score(y_test,ypred3))

0.8307692307692308


In [21]:
#Array method of using different kernels

[{'kernel':['rbf'],'gamma':[1e-3,1e-4],
     'C':[1,10,100,1000]},
{'kernel':['linear'],'C':[1,10,100,1000]},
{'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
{'kernel':['sigmoid'],'C':[1,10,100,1000],'gamma':[1e-3,1e-4,1e-5]}]

[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
 {'degree': [2, 3, 4], 'gamma': [0.001, 0.0001], 'kernel': ['poly']},
 {'C': [1, 10, 100, 1000],
  'gamma': [0.001, 0.0001, 1e-05],
  'kernel': ['sigmoid']}]

In [22]:
params_grid1=[{'kernel':['rbf']},
             {'kernel':['linear']},
             {'kernel':['poly']},
             {'kernel':['sigmoid']}]

In [23]:
from sklearn.model_selection import GridSearchCV
svm_model=GridSearchCV(SVC(),params_grid1,cv=5)
svm_model.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'kernel': ['rbf']}, {'kernel': ['linear']},
                         {'kernel': ['poly']}, {'kernel': ['sigmoid']}])

In [24]:
print('Best score for training data:',svm_model.best_score_,"\n")

#View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n")
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model=svm_model.best_estimator_
Y_pred=final_model.predict(x_test)

Best score for training data: 0.9933333333333334 

Best C: 1.0 

Best Kernel: linear 

Best Gamma: scale 



In [25]:
print(accuracy_score(y_test,Y_pred))

0.9846153846153847
